using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reactive;
using System.Reactive.Linq;
using System.Threading.Tasks;
using mini_pos.Models;
using mini_pos.Services;
using ReactiveUI;

namespace mini_pos.ViewModels;

public class SupplierViewModel : ViewModelBase
{
    private readonly IDatabaseService _databaseService;
    private readonly IDialogService? _dialogService;

    private Supplier? _selectedSupplier;
    public Supplier? SelectedSupplier
    {
        get => _selectedSupplier;
        set => this.RaiseAndSetIfChanged(ref _selectedSupplier, value);
    }

    private string _searchText = string.Empty;
    public string SearchText
    {
        get => _searchText;
        set
        {
            this.RaiseAndSetIfChanged(ref _searchText, value);
            FilterSuppliers();
        }
    }

    private Supplier _currentSupplier = new();
    public Supplier CurrentSupplier
    {
        get => _currentSupplier;
        set => this.RaiseAndSetIfChanged(ref _currentSupplier, value);
    }

    public ObservableCollection<Supplier> AllSuppliers { get; } = new();
    public ObservableCollection<Supplier> Suppliers { get; } = new();

    public ReactiveCommand<Unit, Unit> AddCommand { get; }
    public ReactiveCommand<Unit, Unit> EditCommand { get; }
    public ReactiveCommand<Unit, Unit> DeleteCommand { get; }
    public ReactiveCommand<Unit, Unit> SaveCommand { get; }
    public ReactiveCommand<Unit, Unit> CancelCommand { get; }

    // Interaction to open the window
    public Interaction<Supplier, Unit> ShowDialog { get; } = new();
    public Action? CloseDialogAction { get; set; }

    private bool _isEditMode;

    public SupplierViewModel(IDatabaseService databaseService, IDialogService? dialogService = null)
    {
        _databaseService = databaseService;
        _dialogService = dialogService;

        var canEditOrDelete = this.WhenAnyValue(x => x.SelectedSupplier)
                                  .Select(x => x != null);

        AddCommand = ReactiveCommand.CreateFromTask(async () =>
        {
            _isEditMode = false;
            // Generate ID based on current list count + 1 (or query DB MAX)
            // Ideally should be generated by DB or Service, but for now:
            var maxId = AllSuppliers.Any() 
                ? AllSuppliers.Max(s => int.TryParse(s.Id.Replace("SUP", ""), out var n) ? n : 0) 
                : 0;
            
            CurrentSupplier = new Supplier
            {
                Id = $"SUP{maxId + 1:D3}",
                Sequence = AllSuppliers.Count + 1
            };
            await ShowDialog.Handle(CurrentSupplier);
        });

        EditCommand = ReactiveCommand.CreateFromTask(async () =>
        {
            if (SelectedSupplier != null)
            {
                _isEditMode = true;
                // Clone selected supplier to current
                CurrentSupplier = new Supplier
                {
                    Sequence = SelectedSupplier.Sequence,
                    Id = SelectedSupplier.Id,
                    Name = SelectedSupplier.Name,
                    ContactName = SelectedSupplier.ContactName,
                    Email = SelectedSupplier.Email,
                    Phone = SelectedSupplier.Phone,
                    Address = SelectedSupplier.Address
                };
                await ShowDialog.Handle(CurrentSupplier);
            }
        }, canEditOrDelete);

        DeleteCommand = ReactiveCommand.CreateFromTask(DeleteAsync, canEditOrDelete);

        SaveCommand = ReactiveCommand.CreateFromTask(SaveAsync);
        CancelCommand = ReactiveCommand.Create(Cancel);

        _ = LoadDataAsync();
    }

    public SupplierViewModel() : this(null!, null)
    {
        // Design-time
    }

    private async Task LoadDataAsync()
    {
        if (_databaseService == null) return;
        
        AllSuppliers.Clear();
        var list = await _databaseService.GetSuppliersAsync();
        foreach (var s in list)
        {
            AllSuppliers.Add(s);
        }
        FilterSuppliers();
    }

    private async Task SaveAsync()
    {
        if (string.IsNullOrWhiteSpace(CurrentSupplier.Name))
        {
            if (_dialogService != null)
            {
                await _dialogService.ShowErrorAsync("ກະລຸນາປ້ອນຊື່ຜູ້ສົ່ງ (Supplier name required)");
            }
            return;
        }

        bool success;
        if (_isEditMode)
        {
            success = await _databaseService.UpdateSupplierAsync(CurrentSupplier);
        }
        else
        {
            success = await _databaseService.AddSupplierAsync(CurrentSupplier);
        }

        if (success)
        {
            await LoadDataAsync();
            CloseDialogAction?.Invoke();
            if (_dialogService != null)
            {
                await _dialogService.ShowSuccessAsync("ບັນທຶກຜູ້ສົ່ງສຳເລັດ (Supplier saved)");
            }
        }
        else if (_dialogService != null)
        {
            await _dialogService.ShowErrorAsync("ບັນທຶກຜູ້ສົ່ງບໍ່ສຳເລັດ (Failed to save supplier)");
        }
    }

    private void Cancel()
    {
        CloseDialogAction?.Invoke();
    }

    private async Task DeleteAsync()
    {
        if (SelectedSupplier != null)
        {
            bool confirm = true;
            if (_dialogService != null)
            {
                confirm = await _dialogService.ShowConfirmationAsync("ຢືນຢັນການລຶບ", $"ລຶບຜູ້ສົ່ງ {SelectedSupplier.Name} ຫຼືບໍ່?");
            }

            if (!confirm) return;

            bool success = await _databaseService.DeleteSupplierAsync(SelectedSupplier.Id);
            if (success)
            {
                await LoadDataAsync();
                if (_dialogService != null)
                {
                    await _dialogService.ShowSuccessAsync("ລຶບຜູ້ສົ່ງສຳເລັດ (Supplier deleted)");
                }
            }
            else if (_dialogService != null)
            {
                await _dialogService.ShowErrorAsync("ລຶບຜູ້ສົ່ງບໍ່ສຳເລັດ (Failed to delete supplier)");
            }
        }
    }

    private void FilterSuppliers()
    {
        Suppliers.Clear();
        var query = AllSuppliers.AsEnumerable();

        if (!string.IsNullOrWhiteSpace(SearchText))
        {
            query = query.Where(s => s.Name.Contains(SearchText, StringComparison.OrdinalIgnoreCase) ||
                                     s.Id.Contains(SearchText, StringComparison.OrdinalIgnoreCase));
        }

        foreach (var supplier in query)
        {
            Suppliers.Add(supplier);
        }
    }
}
